name: CI
on:
  push:
    paths:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.tpl.md"
      - "test_data/*.json"
      - ".github/workflows/*.yml"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Print version
        run: deno --version

      - name: Cache all dependencies
        run: |
          shopt -s globstar
          deno cache --no-check **/*.ts

      - name: Check schema bundle is up-to-date
        run: deno run --no-check --quiet --allow-run=deno --allow-read=./src/schemas/mod.bundle.js ./scripts/check_bundle.ts

      - name: Check markdown files are up-to-date
        run: |
          deno run --no-check --quiet tpl.ts > tpl.json
          deno fmt tpl.json
          cat tpl.json
          deno run --no-check --quiet --allow-read=. --allow-run=deno ./scripts/check_markdown.ts < tpl.json

      - name: Run tests (dev bundle)
        run: |
          BUNDLE_RELEASE=0 deno run --no-check --allow-all --unstable --quiet ./scripts/bundle.ts
          deno test --allow-read=./test/example_data --no-check --quiet

      - name: Run tests (release bundle)
        run: |
          BUNDLE_RELEASE=1 deno run --no-check --allow-all --unstable --quiet ./scripts/bundle.ts
          deno test --allow-read=./test/example_data --no-check --quiet
